name: hotel CD

on:
  push:
    branches: [ develop ]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Add test config yaml
        run: |
          mkdir ./src/test/resources; touch ./src/test/resources/application.yaml
          echo "${{secrets.TEST_CONFIG}}" > ./src/test/resources/application.yaml
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Docker build & push
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USER }}/p-ser-hotel .
          docker push ${{ secrets.DOCKER_USER }}/p-ser-hotel
      - name: Execute remote ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd C:\workspace\p-ser-backend && git pull origin develop
            echo "${{secrets.DEV_CONFIG}}" > ./k8s/config/application.yaml
            kubectl apply -k ./k8s
            kubectl rollout restart deployment -n hotel-ns hotel-deployment
